config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root "stories#index"
  
  put 'stories/:id/change_status', to: 'stories#change_status', as: 'change_status'

  resources :stories do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :story
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :users
    has_many :stories
end

app/models/story.rb
class Story < ApplicationRecord
    include AASM

    has_many :comments
    belongs_to :organization
    belongs_to :writer, class_name: 'User', optional: true
    belongs_to :reviewer, class_name: 'User', optional: true

    validates :headline, presence: true

    aasm :column => 'story_status' do
        state :unassigned, initial: true
        state :draft
        state :for_review
        state :in_review
        state :pending
        state :approved
        state :published
        state :archived

        event :set_writer do
            transitions from: :unassigned, to: :draft
        end

        event :request_review do
            transitions from: :draft, to: :for_review
        end
    
        event :start_review do
            transitions from: :for_review, to: :in_review
        end
    
        event :request_changes do
            transitions from: :in_review, to: :pending
        end

        event :back_to_draft do
            transitions from: :pending, to: :draft
        end
    
        event :approve do
            transitions from: :in_review, to: :approved
        end
    
        event :publish do
            transitions from: :approved, to: :published
        end
    
        event :archive do
            transitions from: :approved, to: :archived
        end

    end

    def unassigned?
        story_status == "unassigned"
    end

    def draft?
        story_status == "draft"
    end

    def for_review?
        story_status == "for_review"
    end

    def in_review?
        story_status == "in_review"
    end

    def pending?
        story_status == "pending"
    end

    def approved?
        story_status == "approved"
    end

    def published?
        story_status == "published"
    end

    def archived?
        story_status == "archived"
    end

    def has_body?
        !body.blank?
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories_to_write, class_name: 'Story', foreign_key: 'writer_id'
  has_many :stories_to_review, class_name: 'Story', foreign_key: 'reviewer_id'
  has_many :comments
  belongs_to :organization

  VALID_TYPES = ['chief_editor', 'writer']

  validates :user_type, inclusion: { in: VALID_TYPES }

  def chief_editor?
    user_type == 'chief_editor'
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization

    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @story = Story.find(params[:story_id])
        @comment = @story.comments.create(user_id: current_user.id, body: comment_params[:body])
        redirect_to edit_story_path(@story.id)
    end

    private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_organization

  def index
    @stories = Story.where(organization_id: @organization.id)
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    authorize Story, :chief_editor?

    @story = Story.new
    @users = User.where(organization_slug: current_user.organization_slug).where.not(id: current_user.id)
  end

  def create
    authorize Story, :chief_editor?

    @story = Story.new(headline: story_params[:headline], body: story_params[:body], writer_id: story_params[:writer_id], reviewer_id: story_params[:reviewer_id], organization: @organization)

    if @story.writer_id
      @story.set_writer
    end

    if @story.save
      redirect_to stories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @story = Story.find(params[:id])

    if current_user.chief_editor?
      @users = User.where(organization_slug: current_user.organization_slug).where.not(id: current_user.id)
    end
    
  end

  def update
    @story = Story.find(params[:id])

    if @story.pending?
      @story.back_to_draft
    end
    if story_params[:writer_id] && @story.unassigned?
      @story.set_writer
    end

    if @story.update(story_params)
      redirect_to edit_story_path(@story.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def change_status
    @story = Story.find(params[:id])

    if !current_user.chief_editor? && current_user.id != @story.reviewer_id && current_user.id != @story.writer_id
      render :edit, status: :unprocessable_entity
    else
      case params[:status]
      when "request_review"
        @story.request_review
      when "start_review"
        @story.start_review
      when "request_changes"
        @story.request_changes
      when "approve"
        @story.approve
      when "publish"
        @story.publish
      when "archive"
        @story.archive
      end
  
      if @story.save
        redirect_to edit_story_path(@story.id)
      else
        render :edit, status: :unprocessable_entity
      end
    end

  end

  private
  def story_params
    params.require(:story).permit(:writer_id, :reviewer_id, :comments_open, :headline, :body)
  end

  def set_organization
    @organization = Organization.find_by(slug: current_user.organization_slug)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    added_attrs = [:organization_slug, :email, :password]
    devise_parameter_sanitizer.permit(:sign_in, keys: [added_attrs])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_comment.html.erb
<div class="m-2">
    <div class="text-gray-600">
        <%= comment.user&.name %>:
    </div>

    <div class="border-solid border-2">
        <span class="m-2">
            <%= comment.body %>
        </span>
        
    </div>
</div>

app/views/comments/_form.html.erb
<div class="m-2 mt-4">
    <%= form_with model: [ @story, @story.comments.build ] do |form| %>
        
        <%= form.text_area :body, style:"width:100%", placeholder:'Write a comment...' %>
        
        <div class="flex items-center">
            <div></div>
            <button class="ml-auto">
                <%= form.submit "Post", class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200' %>
            </button>
        </div>



    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="mx-56">
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with model: story do |form| %>

  <div>
    <%= form.label :writer %><br>
    <%= form.select :writer_id, options_for_select(@users.map { |user| [user.email, user.id] }), {}, { class: 'form-control' } %>
  <div>

  <div>
    <%= form.label :reviewer %><br>
    <%= form.select :reviewer_id, options_for_select(@users.map { |user| [user.email, user.id] }), {}, { class: 'form-control' } %>
  <div>

  <div>
    <%= form.label :headline %><br>
    <%= form.text_field :headline %>
    <% story.errors.full_messages_for(:headline).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% story.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/_navbar.html.erb
<div class="grid justify-items-end mt-4">
    <% if user_signed_in? %> 
    <%= button_to "Logout", destroy_user_session_path, method: :delete %> 
    <% else %>
    <%= button_to "Sign in", new_user_session_path %> 
    <% end %>
</div>

<div class="grid justify-items-center">
    <h1 class="font-bold text-2xl"><%= organization.name %></h1>
</div>


<div class="grid justify-items-end">
    <span class="text-xl">
        <%= user.name %>
    </span>
    <span>
        <%= t("user_profile.#{user.user_type}") %>
    </span>
</div>

app/views/stories/_status.html.erb
<% if story.draft? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-gray-300 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% elsif story.for_review? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-cyan-300 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% elsif story.in_review? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-yellow-300 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% elsif story.pending? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-yellow-500 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% elsif story.approved? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-blue-500 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% elsif story.published? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-green-500 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% elsif story.archived? %>
    <button class='border-solid border-2 px-4 py-1 cursor-default bg-cyan-500 w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% else %>
    <button class='border-solid border-2 px-4 py-1 cursor-default w-36'>
        <%= t("story_status.#{story.story_status}") %>
    </button>
<% end %>

app/views/stories/_user.html.erb
<div class="grid justify-items-end">
    <% if user_signed_in? %> 
    <%= button_to "Logout", destroy_user_session_path, method: :delete %> 
    <% else %>
    <%= button_to "Sign in", new_user_session_path %> 
    <% end %>

    <div>
        <span>
            <%= user.name %>
        </span>
        <span>
            <%= user.user_type %>
        </span>
    </div>
</div>

app/views/stories/edit.html.erb
<%= render 'stories/navbar', organization: @organization, user: current_user %>

<h2 class="text-xl"> <%= link_to "Home", stories_path %> > <%= @story.headline %> </h2>

<div class="w-full">
    <div class="border-solid border-2 w-full pb-2 mb-4">


        <%= form_with scope: :story, url: story_path(@story), method: :put do |form| %>
            <div class="mt-6 mx-4">
                <div class="flex items-center">
                    <div>
                        <%= form.label "Headline: " %>
                        <%= form.text_field :headline %>
                        <% @story.errors.full_messages_for(:headline).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div class="ml-auto">
                        <%= render 'stories/status', story: @story %>
                    </div>
                </div>

                <div class="mt-4">
                    <% if current_user.chief_editor? && @story.draft? %>
                        <span>
                            <%= form.label "Writer: " %>
                            <%= form.select :reviewer_id, options_for_select([["", nil]] + @users.map { |user| [user.name, user.id] }, default: @story.writer_id), {}, { class: 'form-control' } %>
                        </span>

                        <span class="ml-4">
                            <%= form.label "Reviewer: " %>
                            <%= form.select :reviewer_id, options_for_select([["", nil]] + @users.map { |user| [user.name, user.id] }), {}, { class: 'form-control' } %>
                        </span>
                    <% else %>
                        <span class="w-64">
                            Writer: <%= @story&.writer != nil ? @story.writer.name : "None" %>
                        </span>
                        <span class="ml-24">
                            Reviewer: <%= @story&.reviewer != nil ? @story.reviewer.name : "None" %>
                        </span>
                    <% end %>

                </div>

                <div class="mt-8 w-full">
                    <%= form.text_area :body, placeholder:'Write a story...', rows: 10 , style: 'width:100%', :disabled => current_user.id != @story.writer_id || !@story.draft? %><br>
                    <% @story.errors.full_messages_for(:body).each do |message| %>
                    <div><%= message %></div>
                    <% end %>
                </div>

                <% if current_user.chief_editor? %>

                    <div class="flex items-center">
                        <div>
                            <% if @story.approved? %>
                                <span>
                                    <%= form.submit 'Publish', 
                                    class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200 w-40',
                                    formaction: change_status_path(id: @story.id, status: "publish"), 
                                    :disabled => !@story.approved? %>
                                </span>

                                <span>
                                    <%= form.submit 'Archive',
                                    class: 'px-4 py-1.5 cursor-pointer bg-gray-500 hover:bg-gray-700 text-slate-200 w-40', 
                                    formaction: change_status_path(id: @story.id, status: "archive"),
                                    :disabled => !@story.approved? %>
                                </span>
                            <% end %>

                        </div>
                        <div class="ml-auto">
                            <% if @story.unassigned? || @story.draft? %>
                                <span>
                                    <%= link_to "Cancel", stories_path, class: 'px-4 py-2 cursor-pointer bg-gray-300 hover:bg-gray-500' %>
                                </span>
                                <span class="ml-2">
                                    <%= form.submit "Save", class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200' %>
                                </span>
                            <% end %>

                        </div>
                    </div>



                <% end %>

                <% if current_user.id == @story.writer_id && !@story.published? %>
                    <div class="flex items-center">
                        <div>
                            <%= form.submit "Request Review",
                                class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200 w-40',
                                formaction: change_status_path(id: @story.id, status: "request_review"), 
                                :disabled => !@story.draft? || !@story.has_body? %>
                        </div>

                        <div class="ml-auto">
                            <span>
                                <%= link_to "Cancel", stories_path, class: 'px-4 py-2 cursor-pointer bg-gray-300 hover:bg-gray-500' %>
                            </span>
                            <span class="ml-2">
                                <%= form.submit "Save", class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200', :disabled => !@story.draft? %>
                            </span>
                        </div>
                    
                    </div>


                <% end %>

                <% if current_user.id == @story.reviewer_id %>
                    <% if @story.for_review? %>
                        <span>
                            <%= form.submit 'Review', 
                            class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200 w-40', 
                            :disabled => !@story.for_review?, 
                            formaction: change_status_path(id: @story.id, status: "start_review") %>
                        </span>
                    <% elsif @story.in_review? %>
                        <span>
                            <%= form.submit 'Approve', 
                            class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200 w-40', 
                            :disabled => !@story.in_review?, 
                            formaction: change_status_path(id: @story.id, status: "approve") %>
                        </span>
                        <span>
                            <%= form.submit 'Request Changes',
                            class: 'px-4 py-1.5 cursor-pointer bg-yellow-500 hover:bg-yellow-700 text-slate-200 w-40', 
                            :disabled => !@story.in_review?, 
                            formaction: change_status_path(id: @story.id, status: "request_changes") %>
                        </span>
                    <% end %>



                <% end %>

                
            </div>
            
        <% end %>


    </div>
</div>


<%# Comments  %>
<% if policy(:story).can_comment?(@story) %>
    <div class="mt-12">
        <h1 class="mb-2 text-xl">Comments (<%= @story.comments&.count() %>)</h1>
        <div  class="border-solid border-2 w-full pb-2 mb-4">
            
            <%= render @story.comments %>

            <% if (@story.draft? && !@story.has_body?) || @story.in_review? %>
                <div class="w-full">
                <%= render 'comments/form' %>
                </div>
                
            <% end %>
        </div>
    </div>
<% end %>

app/views/stories/index.html.erb
<%= render 'stories/navbar', organization: @organization, user: current_user %>

<div>
  <div>
    <h1 class="font-bold text-2xl">Stories</h1>

    <div class="grid justify-items-end mb-4">
      <% unless !current_user.chief_editor?%>
        <%= link_to "New", new_story_path, class: 'border-solid border-2 px-4 py-1 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200' %>
      <% end %>
    </div>
  </div>


  <div class="grid place-items-center  w-full h-full">
    
    <% @stories.each do |story| %>
      <div class="border-solid border-2 w-full pb-2 mb-4">
        <div class="mt-2 mx-2 flex items-center">
          <div class="flex flex-col">
            <h2 class="font-bold text-xl text-gray-500"><%= link_to story.headline, edit_story_path(id: story.id) %></h2>
          </div>
          <div class="ml-auto">
            <%= render 'stories/status', story: story %>
          </div>
        </div>
        <div class="ml-2">
          <span class="w-64">
            Writer: <%= story&.writer != nil ? story.writer.name : "None" %>
          </span>
          <span class="ml-24">
            Reviewer: <%= story&.reviewer != nil ? story.reviewer.name : "None" %>
          </span>

        </div>

      </div>
    <% end %>
  
  </div>
</div>

app/views/stories/new.html.erb
<%= render 'stories/navbar', organization: @organization, user: current_user %>

<h2 class="text-xl"> <%= link_to "Home", stories_path %> > New story </h2>

<div class="w-full">
    <div class="border-solid border-2 w-full pb-2 mb-4">
      <%= form_with scope: :story, url: stories_path(@organization, @story) do |form| %>
      <div class="mt-6 mx-4">
        <div class="flex items-center">
          <div>
            <%= form.label "Headline: " %>
            <%= form.text_field :headline %>
            <% @story.errors&.full_messages_for(:headline).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
          <div class="ml-auto">
            <%= render 'stories/status', story: @story %>
          </div>
        </div>

        <div class="mt-4">
          <span>
            <%= form.label "Writer: " %>
            <%= form.select :writer_id, options_for_select([["", nil]] + @users&.map { |user| [user.name, user.id] }), {}, { class: 'form-control' } %>
          </span>

          <span class="ml-4">
            <%= form.label "Reviewer: " %>
            <%= form.select :reviewer_id, options_for_select([["", nil]] + @users&.map { |user| [user.name, user.id] }), {}, { class: 'form-control' } %>
          </span>
        </div>

        <div class="mt-8 w-full">
          <%= form.text_area :body, placeholder:'Write a story...', rows: 10 , style: 'width:100%', :disabled => true %><br>
          <% @story.errors&.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>

        <div class="flex items-center">
          <div></div>
          <div class="ml-auto">
            <span>
              <%= link_to "Cancel", stories_path, class: 'px-4 py-2 cursor-pointer bg-gray-300 hover:bg-gray-500' %>
            </span>
            <span>
              <%= form.submit "Save", class: 'px-4 py-1.5 cursor-pointer bg-cyan-500 hover:bg-cyan-700 text-slate-200' %>
            </span>
            
          </div>
        </div>
      </div>

      <% end %>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>